### ISSUE TITLE
Something is missing, I keep getting a time out error

### ISSUE THREAD

**Issue by frankpmjr** [Cardknox/Cardknox-Opencart-3.x#1]
Hi, 

I installed and checked all the code but no matter what I do it doesn't work.  I can run the service using Soap UI and I get a response but when I try to run it in the Opencart instance through the Extension it just keeps timing out.  Is there any kind of documentation to troubleshoot what is wrong?  Is there a way to get support?  Also I see that it keeps asking for a transaction key but according to CardKNox there is no transaction key required, only the iframes token.

**Comment by dlehren** [comment]
What is the exact version of open cart that you are using?
You will need a transaction key (regular cardknox key) and a token key (a cardknox key that's used to generate tokens for cardknox ifeilds) for this to work and for it to handle credit cards securely.
This plugin is in development stages and unfortunately does not have full documentation yet, but we are happy to help troubleshoot.

**Comment by frankpmjr** [comment]
Thank you for getting back to me so quickly.  I am using 3.0.2.0 and I have both the transaction key and the iframes key.  I put them both in, saved and the transaction just times out.  Any idea where I can start the troubleshooting?  Thanks.

**Comment by frankpmjr** [comment]
Its now working perfectly, thanks.
